In [1]:
from numpy import loadtxt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc,roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.calibration import calibration_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from scipy.sparse import vstack
from sklearn.model_selection import learning_curve
from sklearn.model_selection import GridSearchCV
from xgboost import plot_tree
from xgboost import plot_importance
import matplotlib.pyplot as plt
import matplotlib.pyplot as pyplot
import pandas as pd
import numpy as np
from tabulate import tabulate
import pickle
import seaborn as sns
import tensorflow as tf
import keras
from collections import Counter
%matplotlib inline
sns.set()

Using TensorFlow backend.


In [23]:
config = tf.ConfigProto(device_count = {'GPU': 1 , 'CPU': 12} ) 
sess = tf.Session(config=config) 
keras.backend.set_session(sess)

In [2]:
df=pd.read_csv('C:/Users/a0019865/Desktop/Analytics Road Map/Workshops/2019 workshop/SAAIR2019/Machine Learning/datasets/defaultcredit.csv')

In [3]:
df.head(2)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   

    ...     BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0   ...           0.0        0.0        0.0       0.0     689.0       0.0   
1   ...        3272.0     3455.0     3261.0       0.0    1000.0    1000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default  
0       0.0       0.0       0.0        1  
1    1000.0       0.0    2000.0        1  

[2 rows x 25 columns]

In [4]:
df.default.value_counts()

0    23364
1     6636
Name: default, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID           30000 non-null int64
LIMIT_BAL    30000 non-null float64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null float64
BILL_AMT2    30000 non-null float64
BILL_AMT3    30000 non-null float64
BILL_AMT4    30000 non-null float64
BILL_AMT5    30000 non-null float64
BILL_AMT6    30000 non-null float64
PAY_AMT1     30000 non-null float64
PAY_AMT2     30000 non-null float64
PAY_AMT3     30000 non-null float64
PAY_AMT4     30000 non-null float64
PAY_AMT5     30000 non-null float64
PAY_AMT6     30000 non-null float64
default      30000 non-null int64
dtypes: float64

In [12]:
df.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [41]:
X = df_processed.drop(['default','ID'],axis=1)
y = df_processed['default']

In [42]:
X.shape

(30000, 33)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from imblearn.under_sampling import (RandomUnderSampler, 
                                     ClusterCentroids,
                                     TomekLinks,
                                     NeighbourhoodCleaningRule,
                                     NearMiss)

# combination of over-sampling and under-sampling
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE

smt = SMOTETomek(ratio='auto')
x_smt, y_smt = smt.fit_sample(x, y)
print('SMOTETomek{}'.format(Counter(y_rs)))

In [44]:
X_train.shape

(24000, 33)

In [45]:
X_test.shape

(6000, 33)

In [46]:
# Create the model with 100 trees
rf = RandomForestClassifier(n_estimators=10,random_state=42)                          
# Fit on training data
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [47]:
from sklearn import datasets, neural_network, metrics, model_selection, preprocessing

In [48]:
metrics.accuracy_score(y_test, rf.predict(X_test))

0.8038333333333333

In [49]:
y_pred = rf.predict(X_test)

In [50]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[4402  285]
 [ 892  421]]
              precision    recall  f1-score   support

           0       0.83      0.94      0.88      4687
           1       0.60      0.32      0.42      1313

   micro avg       0.80      0.80      0.80      6000
   macro avg       0.71      0.63      0.65      6000
weighted avg       0.78      0.80      0.78      6000

0.8038333333333333


# Resampling Methods

In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

# uSING oVERSAMPLING 

In [52]:
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
sm = SMOTE('minority')
X_sm, y_sm = sm.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_sm))

Resampled dataset shape Counter({0: 18661, 1: 18661})


# Cross Validation

Cross-validation is a resampling procedure used to evaluate machine learning models on a limited data sample.

The procedure has a single parameter called k that refers to the number of groups that a given data sample is to be split into. As such, the procedure is often called k-fold cross-validation. When a specific value for k is chosen, it may be used in place of k in the reference to the model, such as k=10 becoming 10-fold cross-validation.


![](https://scikit-learn.org/stable/_images/grid_search_cross_validation.png)


In [53]:
cv = model_selection.cross_val_score(estimator=rf, X=X_sm, y=y_sm, cv=3)

In [54]:
cv

array([0.57595242, 0.93255627, 0.93336013])

In [55]:
cv.mean()

0.8139562726463438

# Parameter Tuning

A model hyperparameter is a configuration that is external to the model and whose value cannot be estimated from data.

    They are often used in processes to help estimate model parameters.
    They are often specified by the practitioner.
    They can often be set using heuristics.
    They are often tuned for a given predictive modeling problem. 
    
    
   ![](https://cambridgecoding.files.wordpress.com/2016/03/gridsearch_cv.png?w=1220&h=812)


In [56]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [50,100]}

In [58]:
from sklearn.metrics import make_scorer
scoring = {'AUC': 'roc_auc', 'Accuracy': make_scorer(accuracy_score)}

In [60]:
CV = GridSearchCV(rf, param_grid, n_jobs= -1,refit='Accuracy',
                  cv=3,verbose=2,return_train_score=True,scoring =scoring)
                  

In [61]:
CV.fit(X_sm, y_sm)

Fitting 3 folds for each of 108 candidates, totalling 324 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   39.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  4.8min
[Parallel(n_jobs=-1)]: Done 324 out of 324 | elapsed:  8.9min finished


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid={'max_features': [2, 3], 'bootstrap': [True], 'min_samples_split': [8, 10, 12], 'max_depth': [80, 90, 100], 'n_estimators': [50, 100], 'min_samples_leaf': [3, 4, 5]},
       pre_dispatch='2*n_jobs', refit='Accuracy', return_train_score=True,
       scoring={'Accuracy': make_scorer(accuracy_score), 'AUC': 'roc_auc'},
       verbose=2)

In [62]:
CV.best_params_

{'bootstrap': True,
 'max_depth': 80,
 'max_features': 3,
 'min_samples_leaf': 3,
 'min_samples_split': 8,
 'n_estimators': 100}

In [63]:
CV.best_score_

0.841273243663255

In [64]:
# Use the best model to make predictions on the testing data.
#
CV.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [65]:
import joblib
joblib.dump(CV.best_estimator_, 'CV_best_random.pkl', compress = 1)

['CV_best_random.pkl']

In [66]:
saved_grid = joblib.load('CV_best_random.pkl')

In [67]:
saved_grid.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
importances = saved_grid.feature_importances_

In [69]:
saved_grid.feature_importances_

array([2.60493515e-02, 3.11586287e-02, 2.49482306e-02, 2.55944183e-02,
       2.51992978e-02, 2.07065150e-02, 1.93935161e-02, 2.26619723e-02,
       2.99922474e-02, 2.82628106e-02, 2.79739375e-02, 2.67719464e-02,
       2.78481189e-02, 2.74049406e-02, 3.04542299e-02, 2.81259932e-02,
       2.62995753e-02, 2.97605813e-02, 2.78329173e-02, 2.81493581e-02,
       6.95247936e-02, 7.62343790e-02, 4.45114893e-06, 6.10657632e-02,
       7.41011623e-02, 4.35869420e-02, 5.23262625e-04, 1.75509434e-03,
       1.69089946e-04, 1.69231971e-04, 5.77294960e-02, 7.87902880e-02,
       1.75745897e-03])

In [70]:
headers = ["name", "score"]
values = sorted(zip(X.columns, saved_grid.feature_importances_), key=lambda X: X[1] * -1)
print(tabulate(values, headers, tablefmt="plain"))

name             score
2          0.0787903
2          0.0762344
2          0.0741012
1          0.0695248
1          0.0610658
1          0.0577295
3          0.0435869
AGE        0.0311586
PAY_AMT1   0.0304542
BILL_AMT1  0.0299922
PAY_AMT4   0.0297606
BILL_AMT2  0.0282628
PAY_AMT6   0.0281494
PAY_AMT2   0.028126
BILL_AMT3  0.0279739
BILL_AMT5  0.0278481
PAY_AMT5   0.0278329
BILL_AMT6  0.0274049
BILL_AMT4  0.0267719
PAY_AMT3   0.0262996
LIMIT_BAL  0.0260494
PAY_2      0.0255944
PAY_3      0.0251993
PAY_0      0.0249482
PAY_6      0.022662
PAY_4      0.0207065
PAY_5      0.0193935
3          0.00175746
5          0.00175509
4          0.000523263
0          0.000169232
6          0.00016909
0          4.45115e-06
